'use client';
import {useEffect,useRef} from 'react';
import {normalizeSearch} from './party-search-utils.mjs';
import {moneyInput} from './supplier-utils.mjs';
const number=value=>Number(value||0).toLocaleString('en-US',{maximumFractionDigits:2});
export function InvoiceShell({title,children,saving=false,editing=null}){
 return <section className="invoiceWorkspace" aria-label={title}><header className="deskHeader"><div><small>عبدالرحمن سولار / المبيعات والمشتريات</small><h1>{title}</h1></div><div className="deskHeaderMeta"><span>{editing?'تعديل فاتورة #'+editing.number:'فاتورة جديدة'}</span><time>{new Date(editing?.date||Date.now()).toLocaleDateString('en-GB')}</time><span>الدينار العراقي · IQD</span></div></header><fieldset className="deskForm" disabled={saving}>{children}</fieldset></section>;
}
export function InvoiceField({label,children,className=''}){return <div className={'deskField '+className}><div className="deskLabel">{label}</div>{children}</div>}
export function InvoiceCatalog({products,items,query,onQuery,onAdd}){
 const words=normalizeSearch(query).split(/\s+/).filter(Boolean);
 const matches=products.filter(p=>{const text=normalizeSearch([p.name,p.code,p.brand,p.category].join(' '));return words.every(w=>text.includes(w))});
 return <aside className="deskCatalog"><div className="deskSectionTitle"><h2>اختيار المواد</h2><span>{matches.length} مادة</span></div><input data-invoice-search aria-label="البحث عن مادة" onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing){e.preventDefault();const first=matches.find(p=>!items.some(i=>i.id===p.id));if(first)onAdd(first)}}} value={query} onChange={e=>onQuery(e.target.value)} placeholder="اسم، كود، براند أو صنف…"/><div className="deskCatalogList">{matches.map(p=>{const added=items.some(i=>i.id===p.id);return <button type="button" className="deskProduct" key={p.id} disabled={added} onClick={()=>onAdd(p)} aria-label={'إضافة '+p.name}><span><b>{p.name}</b><small>{[p.code,p.brand,p.category].filter(Boolean).join(' · ')}</small><small>المتوفر: <strong>{number(p.qty)}</strong></small></span><span className="deskAdd">{added?'✓ مضاف':'+ إضافة'}</span></button>})}{!matches.length&&<p className="deskEmptySmall">{products.length?'لا توجد مادة مطابقة للبحث':'لا توجد مواد مسجلة'}</p>}</div></aside>;
}
export function InvoiceItems({items,products,kind,onEdit,onRemove,landed}){
 const system=kind==='system',tableRef=useRef(null),previousIds=useRef(new Set(items.map(i=>i.id)));
 useEffect(()=>{const added=items.find(i=>!previousIds.current.has(i.id));previousIds.current=new Set(items.map(i=>i.id));if(added){const input=Array.from(tableRef.current?.querySelectorAll('[data-quantity-id]')||[]).find(el=>el.dataset.quantityId===String(added.id));input?.focus({preventScroll:true});input?.select();input?.closest('tr')?.scrollIntoView({block:'nearest'});}},[items]);
 const advance=(e,price=false)=>{if(e.key!=='Enter'||e.nativeEvent.isComposing)return;e.preventDefault();const next=price?e.currentTarget.closest('tr')?.querySelector('[data-invoice-price]'):e.currentTarget.closest('.invoiceWorkspace')?.querySelector('[data-invoice-search]');next?.focus({preventScroll:true});next?.select();};
 return <section className="deskItems" ref={tableRef}><div className="deskSectionTitle"><h2>مواد الفاتورة</h2><span>{items.length} صنف</span></div>{!items.length?<div className="deskEmpty"><span aria-hidden="true">≡</span><h3>ابدأ بإضافة المواد</h3><p>اختر المادة من القائمة، ثم أدخل الكمية{system?'':' والسعر'}.</p></div>:<table className="deskTable"><thead><tr><th>#</th><th>المادة</th><th>المتوفر</th><th>الكمية</th><th>{system?'كلفة الوحدة':kind==='purchase'?'سعر الشراء':'سعر البيع'}</th><th>{system?'الكلفة':'المجموع'}</th><th><span className="deskSrOnly">حذف</span></th></tr></thead><tbody>{items.map((i,index)=>{const stock=Number(products.find(p=>p.id===i.id)?.qty||0),over=kind!=='purchase'&&Number(i.qty)>stock;return <tr key={i.id} className={over?'deskOver':''}><td className="deskIndex">{index+1}</td><td className="deskMaterial"><b>{i.name}</b><small>{[i.code,i.brand,i.category].filter(Boolean).join(' · ')}</small>{kind==='sale'&&<small>كلفة الوحدة: {number(i.cost)} د.ع</small>}{kind==='purchase'&&<small>واصل المخزن: {number(landed(i))} د.ع / وحدة</small>}{over&&<small className="deskWarning">الكمية أكبر من المتوفر</small>}</td><td data-label="المتوفر" className="deskStock">{number(stock)}</td><td data-label="الكمية"><input data-quantity-id={i.id} onKeyDown={e=>advance(e,!system)} aria-label={'الكمية — '+i.name} inputMode="decimal" value={i.qty} aria-invalid={over} onChange={e=>onEdit(i.id,'qty',moneyInput(e.target.value))}/></td><td data-label={system?'كلفة الوحدة':kind==='purchase'?'سعر الشراء':'سعر البيع'}>{system?<b>{number(i.cost)}</b>:<input data-invoice-price onKeyDown={e=>advance(e)} aria-label={(kind==='purchase'?'سعر الشراء — ':'سعر البيع — ')+i.name} inputMode="decimal" value={i.price===''?'':number(i.price)} onChange={e=>onEdit(i.id,'price',moneyInput(e.target.value))}/>}</td><td className="deskLineSum" data-label={system?'الكلفة':'المجموع'}><b>{number(Number(i.qty||0)*Number((system?i.cost:i.price)||0))}</b></td><td className="deskRemoveCell"><button type="button" className="deskRemove" aria-label={'حذف '+i.name} onClick={()=>onRemove(i.id)}>×</button></td></tr>})}</tbody></table>}</section>;
}
export function InvoiceSummary({entries,total,label='الإجمالي',empty=false}){return <div className="deskSummary"><div className="deskSummaryDetails">{entries.map(([title,value])=><div key={title}><span>{title}</span><b>{value}</b></div>)}</div><div className="deskGrand"><span>{label}</span><strong>{empty?'—':number(total)} <small>د.ع</small></strong></div></div>}
export function InvoiceActions({saving,onSave,saveLabel='حفظ الوصل',onPreview,onPdf,onShare,onClear,onCancel,children}){return <><div className="deskActions"><button className="deskSave" onClick={onSave} disabled={saving}>{saving?'جاري الحفظ…':saveLabel}</button><>{onCancel&&<button className="deskCancel" onClick={onCancel}>إلغاء التعديل</button>}</><button onClick={onPreview}>معاينة A4</button><button onClick={onPdf}>حفظ PDF / طباعة</button><button onClick={onShare}>مشاركة</button>{onClear&&<button className="deskClear" onClick={onClear}>تفريغ الفاتورة</button>}</div>{children&&<details className="deskMore"><summary>خيارات نسخة المخزن</summary><div className="deskCopyActions">{children}</div></details>}</>}
