'use client';
import {useRef,useState} from 'react';
import {filteredStock} from './warehouse-utils.mjs';
const categories=['انفيرتر','انفيرتر زراعي','All in One','بطارية','ألواح','مستلزمات','أخرى'];
export default function ProductsManager({products,setProducts,addProduct,brands}){
 const [edit,setEdit]=useState(null),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const form=useRef(null);
 const next=products.reduce((m,p)=>Math.max(m,parseInt(String(p.code||'').replace(/\D/g,''))||0),0)+1,shown=filteredStock(products,query);
 async function submit(e){e.preventDefault();if(busy)return;setBusy(true);setMessage('');try{if(edit){const f=new FormData(e.currentTarget);const ok=await setProducts(products.map(p=>p.id===edit.id?{...p,name:f.get('name').trim(),brand:f.get('brand'),category:f.get('category')}:p));if(ok!==false){setEdit(null);setMessage('تم حفظ تعديل المادة.')}}else{const ok=await addProduct(e);if(ok!==false)setMessage('تم حفظ المادة. يمكنك البحث عنها أدناه للتعديل.')}}finally{setBusy(false)}}
 function beginEdit(p){setEdit(p);setMessage('');window.scrollTo({top:0,behavior:'smooth'});requestAnimationFrame(()=>form.current?.elements.name?.focus())}
 return <section className="productsManager"><form ref={form} key={edit?.id||'new'} onSubmit={submit} className="card reconcileForm"><div className="autoCode"><span>{edit?'تعديل المادة · الكود':'كود المادة'}</span><b>{edit?.code||String(next).padStart(4,'0')}</b></div><label>اسم المادة<input name="name" defaultValue={edit?.name||''} required placeholder="اسم المادة" disabled={busy}/></label><div className="reconcilePair"><label>البراند<select name="brand" defaultValue={edit?.brand||''} required disabled={busy}><option value="" disabled>اختر البراند</option>{brands.map(b=><option key={b.id} value={b.name}>{b.name}</option>)}</select></label><label>الصنف<select name="category" defaultValue={edit?.category||''} required disabled={busy}><option value="" disabled>اختر الصنف</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><button disabled={busy}>{busy?'جاري الحفظ…':edit?'حفظ التعديل':'حفظ المادة'}</button>{edit&&<button type="button" disabled={busy} onClick={()=>setEdit(null)}>إلغاء التعديل</button>}</form>{message&&<p role="status" className="workflowSuccess">{message}</p>}<div className="card materialsSearch"><label>بحث المواد المحفوظة<input aria-label="بحث المواد المحفوظة" placeholder="اسم المادة، الكود، البراند أو الصنف" value={query} onChange={e=>{setQuery(e.target.value);if(e.target.value.trim())setOpen(true)}}/></label><button className="materialsToggle" aria-expanded={open} aria-controls="saved-materials" onClick={()=>setOpen(v=>!v)}><span>المواد المحفوظة ({shown.length})</span><span aria-hidden="true">{open?'▴':'▾'}</span></button>{open&&<div id="saved-materials" className="savedMaterials">{shown.map(p=><article key={p.id} className="savedMaterial"><div><b>{p.name}</b><small>كود: {p.code} • {p.brand} • {p.category}</small></div><div className="rowActions"><button disabled={busy} onClick={()=>beginEdit(p)}>تعديل</button><button disabled={busy} className="dangerMini" onClick={async()=>{if(!confirm('حذف المادة؟'))return;setBusy(true);try{await setProducts(products.filter(x=>x.id!==p.id))}finally{setBusy(false)}}}>حذف</button></div></article>)}{!shown.length&&<p className="empty">لا توجد مادة مطابقة للبحث</p>}</div>}</div></section>;
}
