'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {supabase} from './supabase';
import {downloadPdf} from './pdf-share.mjs';
import {normalizeSearch} from './party-search-utils.mjs';
import {quantity,warehouseDate,movementDocument,escapeHtml} from './warehouse-utils.mjs';

function Icon({name='movement'}){
 const paths={movement:'M4 7h15m-5-5 5 5-5 5M20 17H5m5-5-5 5 5 5',search:'m21 21-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',refresh:'M20 7a9 9 0 1 0 1 8M20 2v6h-6',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12m13 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',share:'m8 9 8-4M8 15l8 4M8 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0M22 4a3 3 0 1 1-6 0 3 3 0 0 1 6 0M22 20a3 3 0 1 1-6 0 3 3 0 0 1 6 0'};
 return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>;
}
const emptyFilters={query:'',product:'',customer:'',from:'',to:''};
const dayInBaghdad=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Baghdad',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const label=r=>r.kind==='stock_adjustment'?'تسوية رصيد':r.kind==='purchase'?'شراء':r.kind==='system'?'بيع منظومة':'بيع جملة';
export default function StockMovements({a4,openA4,shareA4}){
 const [tab,setTab]=useState('materials'),[draft,setDraft]=useState(emptyFilters),[applied,setApplied]=useState(emptyFilters),[direction,setDirection]=useState('all'),[preset,setPreset]=useState('all'),[stock,setStock]=useState([]),[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[exportError,setExportError]=useState(''),[exporting,setExporting]=useState(false),[page,setPage]=useState(0);const request=useRef(0);
 const load=useCallback(async filters=>{const generation=++request.current;setLoading(true);setError('');try{const {data,error}=await supabase.rpc('solar_stock_movements',{product_filter:filters.product?Number(filters.product):null,customer_filter:filters.customer.trim(),date_from:filters.from||null,date_to:filters.to||null});if(generation!==request.current)return;if(error)throw error;setRows(data||[]);setApplied(filters);setPage(0)}catch{if(generation===request.current)setError('تعذر تحميل السجل. اضغط تحديث للمحاولة مرة أخرى.')}finally{if(generation===request.current)setLoading(false)}},[]);
 useEffect(()=>{let live=true;load(emptyFilters);supabase.rpc('solar_stock_quantities').then(({data,error})=>{if(live&&!error)setStock(data||[])});return()=>{live=false;request.current++}},[load]);
 const shown=useMemo(()=>{const codes=new Map(stock.map(p=>[String(p.id),p.code]));const words=normalizeSearch(applied.query).replace(/#/g,'').split(/\s+/).filter(Boolean);return rows.filter(r=>{const text=normalizeSearch([r.name,r.brand,r.category,codes.get(String(r.productId)),r.receiptNo,r.party,r.note,label(r)].join(' '));return words.every(w=>text.includes(w))&&(direction==='all'||(direction==='in'?Number(r.inQty)>0:Number(r.outQty)>0))})},[rows,stock,applied.query,direction]);
 const totals=shown.reduce((s,r)=>({in:s.in+Number(r.inQty||0),out:s.out+Number(r.outQty||0)}),{in:0,out:0}),pageCount=Math.max(1,Math.ceil(shown.length/30)),currentPage=Math.min(page,pageCount-1),visible=shown.slice(currentPage*30,currentPage*30+30);
 const period=applied.from||applied.to?`${applied.from||'البداية'} — ${applied.to||'اليوم'}`:'جميع الفترات';
 const title=applied.customer?'حركة المادة والعميل — '+applied.customer:'سجل حركة المواد';
 const html=()=>a4(title,'<div class="meta"><div>الفترة: '+escapeHtml(period)+'</div><div>نوع الحركة: '+({all:'الكل',in:'دخول',out:'خروج'}[direction])+'</div>'+(applied.query?'<div>البحث: '+escapeHtml(applied.query)+'</div>':'')+'</div>'+movementDocument(shown),'عدد الحركات: '+quantity(shown.length),'بدون أسعار');
 async function exportFile(type){if(exporting)return;setExporting(true);setExportError('');try{if(type==='preview')await openA4(html());else if(type==='download')await downloadPdf(title,html());else await shareA4(title,'',html())}catch{setExportError('تعذر تجهيز المستند. حاول مرة أخرى.')}finally{setExporting(false)}}
 function quickRange(value){const today=dayInBaghdad();let from='';if(value==='today')from=today;if(value==='month')from=today.slice(0,8)+'01';if(value==='week'){const date=new Date(today+'T12:00:00Z');date.setUTCDate(date.getUTCDate()-6);from=date.toISOString().slice(0,10)}const filters={...draft,from,to:value==='all'?'':today};setPreset(value);setDraft(filters);load(filters)}
 function switchTab(value){setTab(value);const filters={...draft,customer:'',product:''};setDraft(filters);load(filters)}
 const edit=(key,value)=>setDraft(s=>({...s,[key]:value}));
 return <section className="movementWorkspace">
  <header className="movementHero"><div className="movementHeroIcon"><Icon/></div><div><h1>حركة المواد</h1><p>الوارد والصادر ورصيد حركة المواد</p></div></header>
  <div className="movementTabs" role="tablist" aria-label="نوع سجل الحركة"><button role="tab" aria-selected={tab==='materials'} aria-controls="movement-panel" id="movement-materials-tab" onClick={()=>switchTab('materials')}>حركة المواد</button><button role="tab" aria-selected={tab==='customer'} aria-controls="movement-panel" id="movement-customer-tab" onClick={()=>switchTab('customer')}>حركة المادة وعميل</button></div>
  <div role="tabpanel" id="movement-panel" aria-labelledby={tab==='materials'?'movement-materials-tab':'movement-customer-tab'}>
  <div className="movementSectionHead"><div className="movementHeading"><span><Icon/></span><div><small>المواد والمخزن</small><h2>{tab==='materials'?'سجل حركة المواد':'حركة المادة والعميل'}</h2></div></div><button className="movementRefresh" disabled={loading} onClick={()=>load(applied)}><Icon name="refresh"/>تحديث</button></div>
  <form className="movementFilters" onSubmit={e=>{e.preventDefault();load({...draft,customer:tab==='customer'?draft.customer:''})}}>
   <label className="movementSearch">المادة أو المستند<div><Icon name="search"/><input aria-label="بحث المادة أو المستند" value={draft.query} onChange={e=>edit('query',e.target.value)} placeholder="قياس، اسم مادة، كود أو رقم مستند"/></div></label>
   {tab==='customer'&&<div className="movementCustomerFields"><label>المادة<select aria-label="المادة" value={draft.product} onChange={e=>edit('product',e.target.value)}><option value="">جميع المواد</option>{stock.map(p=><option key={p.id} value={p.id}>{p.code} • {p.name} • {p.brand}</option>)}</select></label><label>اسم العميل<input aria-label="اسم العميل في الحركة" value={draft.customer} onChange={e=>edit('customer',e.target.value)} placeholder="اكتب اسم العميل أو جزءاً منه"/></label></div>}
   <div className="movementDates"><label>من تاريخ<input aria-label="من تاريخ" type="date" max={draft.to||undefined} value={draft.from} onChange={e=>{edit('from',e.target.value);setPreset('')}}/></label><label>إلى تاريخ<input aria-label="إلى تاريخ" type="date" min={draft.from||undefined} value={draft.to} onChange={e=>{edit('to',e.target.value);setPreset('')}}/></label><button className="movementSubmit" disabled={loading}><Icon name="search"/>{loading?'جاري التحميل…':'عرض السجل'}</button></div>
   <div className="movementQuick"><div className="movementChips" aria-label="اتجاه الحركة">{[['all','الكل'],['in','دخول'],['out','خروج']].map(([value,text])=><button key={value} type="button" aria-pressed={direction===value} onClick={()=>{setDirection(value);setPage(0)}}>{text}</button>)}</div><div className="movementChips movementPeriods" aria-label="الفترة السريعة">{[['today','اليوم'],['week','٧ أيام'],['month','الشهر'],['all','كل الفترات']].map(([value,text])=><button type="button" key={value} aria-pressed={preset===value} onClick={()=>quickRange(value)}>{text}</button>)}</div></div>
  </form>
  <section className="movementResults" aria-label="حركات المواد" aria-busy={loading}>
   <div className="movementResultsHeading"><h2>حركات المواد <span>{quantity(shown.length)} حركة</span></h2><p>{period}</p></div>
   <div className="movementTools"><button disabled={loading||!!error||exporting} onClick={()=>exportFile('preview')}><Icon name="eye"/>معاينة</button><button disabled={loading||!!error||exporting} onClick={()=>exportFile('download')}><Icon name="download"/>{exporting?'تجهيز…':'حفظ PDF'}</button><button className="movementShare" disabled={loading||!!error||exporting} onClick={()=>exportFile('share')}><Icon name="share"/>مشاركة</button></div>
   {exportError&&<p role="alert" className="movementError">{exportError}</p>}
   <div className="movementTotals"><div><span className="movementDot in"/>إجمالي الدخول<b>{quantity(totals.in)}</b></div><div><span className="movementDot out"/>إجمالي الخروج<b>{quantity(totals.out)}</b></div><div>عدد المواد<b>{new Set(shown.map(r=>r.productId)).size}</b></div></div>
   {error?<p className="movementError" role="alert">{error}</p>:loading?<div className="movementEmpty" role="status">جاري تحميل سجل الحركة…</div>:!shown.length?<div className="movementEmpty"><Icon name="search"/><b>لا توجد حركات ضمن البحث</b><span>جرّب مادة أخرى أو وسّع الفترة المحددة.</span></div>:<>
   <div className="movementTable"><div className="movementTableHead"><span>المادة / الطرف</span><span>المستند / التاريخ</span><span>دخول</span><span>خروج</span><span>الرصيد</span></div>{visible.map(r=><article className="movementEntry" key={r.id}><div className="movementMaterial"><b dir="auto">{r.name}</b><small>{[r.brand,r.category].filter(Boolean).join(' • ')}</small><span>{r.kind==='stock_adjustment'?'مطابقة الجرد':r.party||'زبون نقدي'}</span></div><div className="movementDoc"><span className={'movementBadge '+(r.kind==='stock_adjustment'?'adjust':Number(r.inQty)>0?'in':'out')}>{label(r)} <b>#{r.receiptNo}</b></span><time>{warehouseDate(r.date)}</time></div><div className="movementAmount"><small>دخول</small><b>{quantity(r.inQty)}</b></div><div className="movementAmount"><small>خروج</small><b>{quantity(r.outQty)}</b></div><div className="movementAmount movementBalance"><small>الرصيد</small><b>{quantity(r.balance)}</b></div>{r.note&&<p className="movementNote">{r.note}</p>}</article>)}</div>
   {pageCount>1&&<nav className="movementPagination" aria-label="صفحات الحركات"><button disabled={!currentPage} onClick={()=>setPage(p=>p-1)}>السابق</button><span>{currentPage+1} / {pageCount}</span><button disabled={currentPage+1>=pageCount} onClick={()=>setPage(p=>p+1)}>التالي</button></nav>}</>}
   <p className="movementFootnote">الرصيد بعد كل حركة يخص المادة في المخزن كله. ملف PDF يشمل جميع نتائج البحث.</p>
  </section></div>
 </section>;
}
